name: PHP + Symfony Tips
description: 
meta_description: ""

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1
      wrap: false

logo: false
paginate: 15

gems: [jekyll-paginate]

# Details for the RSS feed generator
baseurl:  http://manuelj555.github.io/
#url: 
    
author:         'Manuel Aguirre <programador.manuel@gmail.com>'
encoding: utf-8
