name: PHP + Symfony Tips
description: 
meta_description: ""

#kramdown:
#  input:          GFM
#  syntax_highlighter: pygments

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1
      wrap: false

logo: false
paginate: 15

gems: [jekyll-paginate]

# Details for the RSS feed generator
#baseurl:     
#url: http://localhost/manuelj555.github.io/kasper-master/_site
    
author:         'Manuel Aguirre <programador.manuel@gmail.com>'
encoding: utf-8